/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Observation */
        post: operations["upload_observation_api_sessions__session_id__observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/observations/{observation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Observation */
        get: operations["get_observation_api_sessions__session_id__observations__observation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/guidance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Guidance */
        get: operations["get_guidance_api_sessions__session_id__guidance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_api_sessions__session_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Results */
        post: operations["export_results_api_sessions__session_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Session */
        post: operations["cancel_session_api_sessions__session_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Diagnostics */
        get: operations["get_diagnostics_api_sessions__session_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreatedSession */
        CreatedSession: {
            /** Id */
            id: string;
            /** Access Secret */
            access_secret: string;
            /** Revision */
            revision: number;
            /** Stage */
            stage: string;
        };
        /** DeleteResult */
        DeleteResult: {
            /** Deleted */
            deleted: boolean;
        };
        /** DiagnosticEvent */
        DiagnosticEvent: {
            /** Id */
            id: number;
            /** Observation Id */
            observation_id: string | null;
            /** Event */
            event: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: number;
        };
        /** DiagnosticsState */
        DiagnosticsState: {
            /** Revision */
            revision: number;
            /** Events */
            events: components["schemas"]["DiagnosticEvent"][];
        };
        /** ExportState */
        ExportState: {
            /** Revision */
            revision: number;
            /** Rows */
            rows: components["schemas"]["ResultRow"][];
            /** Unresolved */
            unresolved: {
                [key: string]: unknown;
            }[];
            /** Conflicts */
            conflicts: {
                [key: string]: unknown;
            }[];
            /** Text */
            text: string;
        };
        /** Guidance */
        Guidance: {
            /**
             * Action
             * @enum {string}
             */
            action: "move_left" | "move_right" | "move_up" | "move_down" | "closer" | "farther" | "tilt_left" | "tilt_right" | "hold_still" | "improve_lighting" | "show_full_pattern" | "scan_next" | "complete" | "inconclusive" | "stop";
            /** Reason */
            reason?: string | null;
            target?: components["schemas"]["GuidanceTarget"] | null;
        };
        /** GuidanceState */
        GuidanceState: {
            /** Revision */
            revision: number;
            guidance: components["schemas"]["Guidance"];
        };
        /** GuidanceTarget */
        GuidanceTarget: {
            /** Observation Id */
            observation_id: string;
            /** Box */
            box: number[];
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ObservationState */
        ObservationState: {
            /** Id */
            id: string;
            /** Observation Id */
            observation_id: string;
            /** Revision */
            revision: number;
            /** Status */
            status: string;
            /** Session Id */
            session_id: string;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
        };
        /** QueuedObservation */
        QueuedObservation: {
            /** Id */
            id: string;
            /** Observation Id */
            observation_id: string;
            /** Revision */
            revision: number;
            /** Status */
            status: string;
        };
        /** ResultRow */
        ResultRow: {
            /** Pa */
            pa: string;
            /** Flow */
            flow: string;
            /** Acceleration */
            acceleration: string;
            /** Pattern Id */
            pattern_id: string | null;
            /** Evidence */
            evidence: string[];
        };
        /** ResultsState */
        ResultsState: {
            /** Revision */
            revision: number;
            /** Rows */
            rows: components["schemas"]["ResultRow"][];
            /** Unresolved */
            unresolved: {
                [key: string]: unknown;
            }[];
            /** Conflicts */
            conflicts: {
                [key: string]: unknown;
            }[];
        };
        /** SessionState */
        SessionState: {
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Patterns */
            patterns: {
                [key: string]: unknown;
            }[];
            /** Observation Count */
            observation_count: number;
            guidance: components["schemas"]["Guidance"];
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedSession"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-session-secret"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-session-secret"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_observation_api_sessions__session_id__observations_post: {
        parameters: {
            query?: never;
            header: {
                "x-idempotency-key": string;
                "x-session-secret"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
                "image/webp": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedObservation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_observation_api_sessions__session_id__observations__observation_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-session-secret"?: string | null;
            };
            path: {
                session_id: string;
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_guidance_api_sessions__session_id__guidance_get: {
        parameters: {
            query?: never;
            header?: {
                "x-session-secret"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidanceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_api_sessions__session_id__results_get: {
        parameters: {
            query?: never;
            header?: {
                "x-session-secret"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_results_api_sessions__session_id__export_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-secret"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_session_api_sessions__session_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-session-secret"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostics_api_sessions__session_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-session-secret"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
